export enum EIcon {
    headerCatalogBtnLeftIcon = 'headerCatalogBtnLeftIcon',
    headerCatalogBtnRightIcon = 'headerCatalogBtnRightIcon',
    headerMapIcon = 'headerMapIcon',
    headerOpenIcon = 'headerOpenIcon',
    headerTelegramIcon = 'headerTelegramIcon',
    headerChatsIcon = 'headerChatsIcon',
    headerFavoritesIcon = 'headerFavoritesIcon',
    headerCartIcon = 'headerCartIcon',
    headerLkIcon = 'headerLkIcon',   
    openTechReqIcon = 'openTechReqIcon',
    feedbackAttachFileIcon = 'feedbackAttachFileIcon',
    communicationMethodCallIcon = 'communicationMethodCallIcon',
    communicationMethodEmailIcon = 'communicationMethodEmailIcon',
    communicationMethodTelegramIcon = 'communicationMethodTelegramIcon',
    communicationMethodWhatsappIcon = 'communicationMethodWhatsappIcon',
    feedbackSubmitBtnIcon = 'feedbackSubmitBtnIcon',
    attachedFileDelete = 'attachedFileDelete',
    footerPhoneIcon = 'footerPhoneIcon',
    footerEmailIcon = 'footerEmailIcon',
    footerChatIcon = 'footerChatIcon',
    footerMobileCatalogIcon = 'footerMobileCatalogIcon',
    footerMobileCartIcon = 'footerMobileCartIcon',
    footerMobileRequestsIcon = 'footerMobileRequestsIcon',
    footerMobileChatsIcon = 'footerMobileChatsIcon',
    footerMobileLkIcon = 'footerMobileLkIcon'
}